### ISSUE TITLE
WBE seems to crash some other gnome shell extensions.

### ISSUE THREAD

**Issue by FJoeXXL2** [lviggiani/gnome-shell-extension-wbe#17]
Other extensions which are "affected" by enabling/installling WBE; here are some examples:

System Monitor by darkst:
https://extensions.gnome.org/extension/120/system-monitor/
( https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet )

gTile by vibou_:
https://extensions.gnome.org/extension/28/gtile/
( https://github.com/vibou/vibou.gTile )

Media player indicator by eon:
https://extensions.gnome.org/extension/55/media-player-indicator/
( https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer )

All/some get an "ERROR" status (on the configuration page https://extensions.gnome.org/local/ ) for me, when WBE is enabled or don't work. I'm willing to provide further Info on request and might help you to locate/solve the problem (if possible, i'm not a programmer but willing to learn ^^).

**Comment by UshakovVasilii** [comment]
Hi,
I don't reasons, but the following code:
```
Array.prototype.contains = function(obj) {
    var i = this.length;
    while (i--) {
        if (this[i] === obj) {
            return true;
        }
    }
    return false;
}
```
broke all Arrays functions in other extensions (them got errors like `.indexOf is not a function`, `.split is not a function`)

You can replace
`flag = flag && !excludeList.contains(window.wm_class);`
to
`flag = flag && excludeList.indexOf(window.wm_class) < 0;`
