### ISSUE TITLE
3.20 support

### ISSUE THREAD

**Issue by nos1609** [lviggiani/gnome-shell-extension-wbe#27]
Awaiting for Gnome 3.20 support. Thank You!

**Comment by RenzeNZ** [comment]
Still waiting. As far as I know it only requires a change to the metadata, but I guess the author just doesn't care.

**Comment by lviggiani** [comment]
There you go.
@RenzeNZ: the source code is here. If you know how to fix something, next time please check the source out, do the fixing and push it upstream instead of guessing what the author cares. The project is on github for that purpose.

**Comment by RenzeNZ** [comment]
Well, it got you to do something, so my comment was productive. You could do with some thicker skin, however.

**Comment by lviggiani** [comment]
Next time you could also be more productive, that's the point you missed. However, you put the thing on a personal level with your comment, not me.
