### ISSUE TITLE
Add support for gnome-shell 3.22

### ISSUE THREAD

**Issue by yafp** [lviggiani/gnome-shell-extension-wbe#31]
Hi,

i've tested your extension with gnome shell 3.22.2 on fedora 25.
It works as expected and therefor i added a pull request.

Feel free to use or do whatever else ;)

Greetings & thanks for this great extension.

**Comment by lviggiani** [comment]
Hi, thanks for updating metadata. Your pull request has been merged.
Cheers.

Il lun 5 dic 2016, 08:34 fidel <notifications@github.com> ha scritto:

**Comment by yafp** [comment]
thanks
